// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notes.sql

package db

import (
	"context"
	"database/sql"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, title, body)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, body, created_at, updated_at
`

type CreateNoteParams struct {
	UserID int64
	Title  string
	Body   string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.UserID, arg.Title, arg.Body)
	var i Note
	err := row.Scan(&i.ID, &i.UserID, &i.Title, &i.Body, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes WHERE id = $1 AND user_id = $2
`

type DeleteNoteParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNote = `-- name: GetNote :one
SELECT id, user_id, title, body, created_at, updated_at
FROM   notes WHERE id = $1 AND user_id = $2
`

type GetNoteParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, arg.ID, arg.UserID)
	var i Note
	err := row.Scan(&i.ID, &i.UserID, &i.Title, &i.Body, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const patchNote = `-- name: PatchNote :one
UPDATE notes
SET    title = COALESCE($3, title), body = COALESCE($4, body), updated_at = now()
WHERE  id = $1 AND user_id = $2
RETURNING id, user_id, title, body, created_at, updated_at
`

type PatchNoteParams struct {
	ID     int64
	UserID int64
	Title  sql.NullString
	Body   sql.NullString
}

func (q *Queries) PatchNote(ctx context.Context, arg PatchNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, patchNote, arg.ID, arg.UserID, arg.Title, arg.Body)
	var i Note
	err := row.Scan(&i.ID, &i.UserID, &i.Title, &i.Body, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET title = $3, body = $4, updated_at = now()
WHERE  id = $1 AND user_id = $2
RETURNING id, user_id, title, body, created_at, updated_at
`

type UpdateNoteParams struct {
	ID     int64
	UserID int64
	Title  string
	Body   string
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote, arg.ID, arg.UserID, arg.Title, arg.Body)
	var i Note
	err := row.Scan(&i.ID, &i.UserID, &i.Title, &i.Body, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
